### ISSUE TITLE
iverilog version update

### ISSUE THREAD

**Issue by dlmiles** [TinyTapeout/tt08-verilog-template#1]
```
My gl_test pass but my test fail, but locally my test pass... is this due to difference in support in:

    iverlog 1.8.1 with icarus 11.0 (stable) used in GH Action (since requirements.txt change that forces 1.8.1 by default not *dev edition used in previous TT) and
    iverlog v1.9.0.dev0 with icarus 13.0 (devel) used locally

Seems there is a verilog feature missing causing the error 
Seems Icarus 11.0 is from Sep2020 (4y ago) maybe that is something we can upgrade for TT07
```

Useful links:

https://packages.ubuntu.com/search?keywords=iverilog&searchon=sourcenames

https://github.com/steveicarus/iverilog

**Comment by dlmiles** [comment]
If there is no obvious ubuntu distribution .deb being maintained that is compatible with GHA.  Then an alternative maybe to clone the official repo, setup workflow to build and test and run action https://github.com/marketplace/actions/build-deb-action and then perform a release (publishing your own .deb to the github release area) manually as and when needed.
You'd probably want to organise the package name to include the gha ubuntu version such as 'gha-ubuntu-22.04-iverilog-12.0-amd64.deb' so when the day comes to change GHA ubuntu version you  just respin them and they get a new name 24.04.

Then add to tt-gds-action a package installer action that might work like

```
  from: TinyTapeout/tt-gds-action/install-packages
  with:
    packages:
      - iverlog@12.0
  # omitting the version should be allowed to install the lastest GA/stable release channel provided
```

The action would have a list of alternative packages that are compatible with GH and understand how to locate and install them.  the mechanism can be extended for anything (magic/ngspice/klayout) etc.. when setup
